# Generated by Django 5.1 on 2024-09-05 13:18
# Tento súbor 0001_initial.py v adresári migrations je automaticky generovaný Django migráciami, 
# ktoré sledujú zmeny v databázových modeloch. V tomto prípade sa jedná o počiatočnú migráciu 
# (initial migration), ktorá vytvára potrebné tabuľky pre tvoje databázové modely.

from django.db import migrations, models


class Migration(migrations.Migration):
    # Toto označuje, že ide o prvú migráciu pre aplikáciu (teda počiatočnú migráciu).
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
