# Generated by Django 5.1 on 2024-11-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('boolean', 'Yes/No'), ('choice', 'Multiple Choice')], default='boolean', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
