# Generated by Django 5.1 on 2024-11-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthApp', '0003_test_created_by_testsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('boolean', 'Yes/No'), ('choice', 'Multiple Choice'), ('text', 'Text Response')], default='boolean', max_length=50),
        ),
    ]
