# Generated by Django 5.1 on 2024-11-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthApp', '0005_alter_question_options_questionanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsubmission',
            name='user',
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='test_code',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
