# Generated by Django 5.1 on 2024-12-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthApp', '0007_test_test_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
    ]
