# Generated by Django 5.1 on 2024-12-21 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthApp', '0008_remove_question_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_points', models.PositiveIntegerField()),
                ('max_points', models.PositiveIntegerField()),
                ('response', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='MentalHealthApp.test')),
            ],
        ),
    ]
