# Generated by Django 5.1 on 2024-12-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthApp', '0009_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, default='Nezaradená', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='category',
            field=models.CharField(blank=True, default='Nezaradená', max_length=100, null=True),
        ),
    ]
