# Generated by Django 5.1 on 2024-12-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthApp', '0010_question_category_questionanswer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='category',
            field=models.CharField(default='Nezaradená', max_length=100),
        ),
    ]
