# Generated by Django 5.1 on 2025-01-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthApp', '0013_alter_question_question_type_drawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='user',
        ),
    ]
