# Generated by Django 5.1 on 2025-02-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthApp', '0016_recordedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='MentalHealthApp.imagemodel'),
        ),
    ]
