# Generated by Django 5.1 on 2025-02-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthApp', '0017_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
