# Generated by Django 5.1 on 2025-05-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentalHealthApp', '0018_remove_question_image_question_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('testId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentalHealthApp.test')),
            ],
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='question',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.DeleteModel(
            name='Drawing',
        ),
    ]
