"""
Django settings for DjangoAPI project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR definuje základný adresár projektu. Týmto sa získa cesta k hlavnému priečinku projektu. (vymazat bo 2x)
BASE_DIR=Path(__file__).resolve(strict=True).parent.parent
# MEDIA_URL určuje URL, cez ktorú budú dostupné mediálne súbory (napr. obrázky nahrané používateľmi). 
# V tomto prípade sú mediálne súbory dostupné cez URL /Photos/.
# MEDIA_URL='/Photos/'
# # MEDIA_ROOT definuje fyzickú cestu, kde budú uložené mediá
# MEDIA_ROOT=os.path.join(BASE_DIR,"Photos")
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR definuje základný adresár projektu. Týmto sa získa cesta k hlavnému priečinku projektu.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lv!d(=ddz9_gr2m7y@rj0ejnrm5k-a7i*e_hy=e_kb=^(hc8p5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',#Tento balík pridáva podporu pre CORS (Cross-Origin Resource Sharing), čo umožňuje, aby iné domény mohli pristupovať k API.
    # 'EmployeeApp.apps.EmployeeappConfig',
    'MentalHealthApp.apps.MentalhealthappConfig'
    
    
]
CORS_ORIGIN_ALLOW_ALL = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# TEMPLATES: Toto nastavenie definuje šablóny (HTML), ktoré sa používajú na renderovanie stránok.
# APP_DIRS = True: Umožňuje Django automaticky hľadať šablóny v adresári každej aplikácie (templates priečinok).
# DIRS = []: Ak máš šablóny na špecifickom mieste mimo štandardného umiestnenia, pridaj cestu sem.
# context_processors: Definuje zoznam procesorov, ktoré pripoja dáta k šablónam. Napríklad request, auth, atď., 
# umožnia šablóne prístup k autentifikovanému používateľovi alebo požiadavke.


WSGI_APPLICATION = 'DjangoAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mentalhealthdb',
        'USER':'Lukas',
        'PASSWORD':'Postgres1',
        'HOST':'mystudentdb.postgres.database.azure.com',
        'PORT':'5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# SESSION_COOKIE_NAME = 'sessionid'
# SESSION_COOKIE_SECURE = False  # Nastav na True pre HTTPS
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_AGE = 1209600

AUTH_USER_MODEL = 'MentalHealthApp.User'
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = [
    'http://localhost:8080',  # URL tvojej frontendovej aplikácie (Vue.js)
]